### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by felzend** [cloudamqp/amqp-client.js#10]
`
const AMQPClient = require('@cloudamqp/amqp-client');
`

**Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: node_modules\@cloudamqp\amqp-client\src\amqp-socket-client.mjs**

`
"@cloudamqp/amqp-client": "^1.1.6"
`

`$ node -v
v14.18.1`

**Comment by carlhoerberg** [comment]
THank you for reporting! Please try 1.1.7 that was just relases, it should automatically require teh rolled up commonjs verson of the lib
