### ISSUE TITLE
cannot connect browser websocket library to deployed instance of rabbitmq

### ISSUE THREAD

**Issue by nuel77** [cloudamqp/amqp-client.js#11]
i have deployed a free rabbitmq instance using cloudrabbit mq, with hostname "vulture.rmq.cloudamqp.com", i tried to connect to this domain. 

![image](https://user-images.githubusercontent.com/50878033/145216851-d5f2d2be-2956-4e14-bdca-a8c061dafc22.png)

```js
const amqp = new AMQPWebSocketClient(
  "wss://vulture.rmq.cloudamqp.com/ws/amqp",
  "pyxvoxaf",
  "pyxvoxaf",
  "password"
);
const conn = await amqp.connect()
console.log(conn)
```
But the websocket connection always fails.

![image](https://user-images.githubusercontent.com/50878033/145217149-3f57bc26-946a-4410-bf18-b21ec9a3b801.png)

anything i am doing wrong here? ..  I am connecting from localhost:3000

**Comment by carlhoerberg** [comment]
Ok, websocket-tcp-relay isn't installed on all shared servers. Will deploy it today.

**Comment by carlhoerberg** [comment]
It should be enabled on all cloudamqp shared servers now (and all dedicated created since 6-12 months or so back). Please reopen if it still doesn't work.

**Comment by nuel77** [comment]
i am still getting the same  error..
![image](https://user-images.githubusercontent.com/50878033/145756446-2cc8da80-a10e-42c2-9791-761c8060c31f.png)
``` js
const url = `wss://${"vulture.rmq.cloudamqp.com"}`;
    const amqp = new AMQPWebSocketClient(
      url,
      "pyxvoxaf",
      "pyxvoxaf",
      "PASSWORD"
    );
 ```
