### ISSUE TITLE
Use JWT when connect to broker

### ISSUE THREAD

**Issue by mxxnseat** [cloudamqp/amqp-client.js#115]
I have set up rabbitmq server to use oauth2 now I'm interesting how to use `AMQPWebSocketClient` to authenticate connection.

I tried make something like this, but got error - `connection closed: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN` and it's expected cuz client connects by username and passcode
```js
const amqp = new AMQPWebSocketClient("ws://localhost:15670", "/");
const conn = await amqp.connect();
await amqp.updateSecret(
"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNRR0Q5eU9aREhyaFBKaTdjQkg5WSJ9.eyJpc3MiOiJodHRwczovL2Rldi0zN2l2aGxidDBhbjE3NHYyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2Njc2YmFiODYxYjI2MWY2NDNhNmQ2YjQiLCJhdWQiOlsiaHR0cHM6Ly9kZXYtMzdpdmhsYnQwYW4xNzR2Mi51cy5hdXRoMC5jb20vYXBpL3YyLyIsImh0dHBzOi8vZGV2LTM3aXZobGJ0MGFuMTc0djIudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTcxOTA1NzA4NCwiZXhwIjoxNzE5MDY0Mjg0LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiYXpwIjoiWjNEbTBRWXhlbDREYkJZQ0ZzUDdYQTBtaEg5MklHaHYifQ.FsDJhUZ0ybiIV8C1pAxn6eDwlVoq6rVYcU6JywSU7Lm4sELz2LffzxJzxN_gabJHSh1C49WG5yU1LvLSep448u6sz5b7W2OSsHaCznolhc5T2JvjrYybtxD1Vph_eU8Aozb1ScfV-hz6W2emRloKh9kVTWUUUTzlpB5lE_L3GiEQExU6XWJy_GRbJ5bBA15nQmunDmtT-gQYKcYn1FSdyPwThQN_rr7UkfgSG_Yg-gsYIkl-X-qvvpJ0EtRIEuMn-n_OTfzB5sQhu6t5BLOI55pvK8g9pjIVNSHJGeD9RcnivmPKNas24SoCrSxKQAwMimLIraedysHLnoLsn1LqEw",
  "jwt"
);
```

**Comment by carlhoerberg** [comment]
On first connect then pass the JWT token in the password field: 

```js
const jwtToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNRR0Q5eU9aREhyaFBKaTdjQkg5WSJ9.eyJpc3MiOiJodHRwczovL2Rldi0zN2l2aGxidDBhbjE3NHYyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2Njc2YmFiODYxYjI2MWY2NDNhNmQ2YjQiLCJhdWQiOlsiaHR0cHM6Ly9kZXYtMzdpdmhsYnQwYW4xNzR2Mi51cy5hdXRoMC5jb20vYXBpL3YyLyIsImh0dHBzOi8vZGV2LTM3aXZobGJ0MGFuMTc0djIudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTcxOTA1NzA4NCwiZXhwIjoxNzE5MDY0Mjg0LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiYXpwIjoiWjNEbTBRWXhlbDREYkJZQ0ZzUDdYQTBtaEg5MklHaHYifQ.FsDJhUZ0ybiIV8C1pAxn6eDwlVoq6rVYcU6JywSU7Lm4sELz2LffzxJzxN_gabJHSh1C49WG5yU1LvLSep448u6sz5b7W2OSsHaCznolhc5T2JvjrYybtxD1Vph_eU8Aozb1ScfV-hz6W2emRloKh9kVTWUUUTzlpB5lE_L3GiEQExU6XWJy_GRbJ5bBA15nQmunDmtT-gQYKcYn1FSdyPwThQN_rr7UkfgSG_Yg-gsYIkl-X-qvvpJ0EtRIEuMn-n_OTfzB5sQhu6t5BLOI55pvK8g9pjIVNSHJGeD9RcnivmPKNas24SoCrSxKQAwMimLIraedysHLnoLsn1LqEw"
const amqp = new AMQPWebSocketClient("ws://localhost:15670", "/", "", jwtToken);
```

Only if the token is about to expire do you need to call `updateSecret`.

**Comment by mxxnseat** [comment]
> On first connect then pass the JWT token in the password field:
> 
> ```js
> const jwtToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNRR0Q5eU9aREhyaFBKaTdjQkg5WSJ9.eyJpc3MiOiJodHRwczovL2Rldi0zN2l2aGxidDBhbjE3NHYyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2Njc2YmFiODYxYjI2MWY2NDNhNmQ2YjQiLCJhdWQiOlsiaHR0cHM6Ly9kZXYtMzdpdmhsYnQwYW4xNzR2Mi51cy5hdXRoMC5jb20vYXBpL3YyLyIsImh0dHBzOi8vZGV2LTM3aXZobGJ0MGFuMTc0djIudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTcxOTA1NzA4NCwiZXhwIjoxNzE5MDY0Mjg0LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiYXpwIjoiWjNEbTBRWXhlbDREYkJZQ0ZzUDdYQTBtaEg5MklHaHYifQ.FsDJhUZ0ybiIV8C1pAxn6eDwlVoq6rVYcU6JywSU7Lm4sELz2LffzxJzxN_gabJHSh1C49WG5yU1LvLSep448u6sz5b7W2OSsHaCznolhc5T2JvjrYybtxD1Vph_eU8Aozb1ScfV-hz6W2emRloKh9kVTWUUUTzlpB5lE_L3GiEQExU6XWJy_GRbJ5bBA15nQmunDmtT-gQYKcYn1FSdyPwThQN_rr7UkfgSG_Yg-gsYIkl-X-qvvpJ0EtRIEuMn-n_OTfzB5sQhu6t5BLOI55pvK8g9pjIVNSHJGeD9RcnivmPKNas24SoCrSxKQAwMimLIraedysHLnoLsn1LqEw"
> const amqp = new AMQPWebSocketClient("ws://localhost:15670", "/", "", jwtToken);
> ```
> 
> Only if the token is about to expire do you need to call `updateSecret`.

Thank you

**Comment by mikhail-fedosenko** [comment]
Was trying the following code, but it gave me "Unauthorized error".
`const amqp = new AMQPWebSocketClient("ws://localhost:15670", "/", "", jwtToken);`
Turned out I also need to pass username too! Like this:
`const amqp = new AMQPWebSocketClient("ws://localhost:15670", "/", "username", jwtToken);`
