### ISSUE TITLE
Pausing queue is not document or implemented ?

### ISSUE THREAD

**Issue by geminigeek** [cloudamqp/amqp-client.js#116]
hi,

i read the api docs, i could not find some thing like whats available in lavinmq http api to pause a queue https://docs.lavinmq.com/http-api.html#tag/queues/operation/PauseQueue 

is there a way to pause queue with this client ?

**Comment by kickster97** [comment]
Hi, thanks for you input :) 
This library implements the basic amqp spec, and pausing a queue is a http feature which is to LavinMQ.
You can use lavinmqctl or the REST-api with any http client to pause queues in LavinMQ.
