### ISSUE TITLE
Compatibility with rabbitmq broker hosted on amazon mq

### ISSUE THREAD

**Issue by CodeWithOz** [cloudamqp/amqp-client.js#13]
How can this package be used in the browser with a rabbitmq instance that is hosted on amazon mq? It seems that the tcp relay is needed in some way, but I'm not sure how that would work with the amazon mq. Thanks.

**Comment by johanrhodin** [comment]
Yes you would have to convince Amazon MQ to install the `websocket-tcp-relay`

Or just go with CloudAMQP where it comes as default :)
