### ISSUE TITLE
amqp websockets on Little Lemur free plan

### ISSUE THREAD

**Issue by CodeWithOz** [cloudamqp/amqp-client.js#14]
I signed up on the free plan to try the amqp over websockets protocol but I can't find the websocket url that should be used with this library. More so the [docs page](https://www.cloudamqp.com/docs/amqp_over_websockets.html) says that the amqp websockets plugin is pre-installed on dedicated instances, but the free plan is a shared instance. Does this mean I can't test the amqp websockets on the free plan?

**Comment by carlhoerberg** [comment]
Websockets are available for all plans, I've updated the docs accordingly. 

The connection string is also descibed at the bottom of that page. 

```js
const url = `wss://test-small-ivory-rat.rmq2.cloudamqp.com/ws/amqp`
const amqp = new AMQPWebSocketClient(url, "VHOST", "USERNAME", "YOUR_PASSWORD")
```

**Comment by CodeWithOz** [comment]
Thanks! Yes some reading plus trial and error eventually led me to that haha.
