### ISSUE TITLE
Creating non-admin users

### ISSUE THREAD

**Issue by CodeWithOz** [cloudamqp/amqp-client.js#15]
Do dedicated plans allow creation of non-admin users? In other words, do dedicated plans give full admin privileges to the account owner? I'm currently testing out the free tier and I understand that shared instances rely on named vhosts to distinguish different users who are on shared plans, so each of those users can't be made an admin of the instance. I want to use a structure whereby I give different users non-admin access to the instance, configured to only have read/write access to specific queues. This way they can connect individually to the broker without being able to affect other users' queues. I can do this when I have full admin privileges to the broker, so I'd like to know if I would get that on the dedicated plans. Thanks.

**Comment by jage** [comment]
Hi,

> Do dedicated plans allow creation of non-admin users?

Yes

> In other words, do dedicated plans give full admin privileges to the account owner?

Yes, you can add vhosts, users, permissions etc on dedicated plans. 

> I'm currently testing out the free tier and I understand that shared instances rely on named vhosts to distinguish different users who are on shared plans, so each of those users can't be made an admin of the instance. 

Correct.

> I want to use a structure whereby I give different users non-admin access to the instance, configured to only have read/write access to specific queues. This way they can connect individually to the broker without being able to affect other users' queues. I can do this when I have full admin privileges to the broker, so I'd like to know if I would get that on the dedicated plans

Yeah, sounds like a good plan and dedicated is the way to go. :)

If you have more questions regarding CloudAMQP feel free to contact us at support@cloudamqp.com.
