### ISSUE TITLE
Range Error

### ISSUE THREAD

**Issue by charleslukes** [cloudamqp/amqp-client.js#19]
I get this error when I listen for events sometimes not sure what to do on my end. 
<img width="973" alt="Screenshot 2021-12-29 at 09 59 05" src="https://user-images.githubusercontent.com/20547232/147692145-4345daad-5be0-4cc3-a9c0-57c215e95c20.png">

**Comment by carlhoerberg** [comment]
Ok, are you able to use wireshark when this is happening to record the
traffic?

**Comment by charleslukes** [comment]
hey so I'm not sure what you need with wireshark. May be you can guide on what specific things I should get from it. 
PS: This is my first time of hearing about wireshark :)

**Comment by carlhoerberg** [comment]
I've released a new version, 1.3.1, that will include more information when this bug happens. Would you mind try that? Also, the web inspector, can you snapshot the WebSocket traffic when this happens?

**Comment by charleslukes** [comment]
just tried again here it is 
![Screenshot 2022-01-11 at 10 21 00](https://user-images.githubusercontent.com/20547232/148916065-16d756c3-0c72-4b3f-b041-1b0d5454a5ed.png)

**Comment by carlhoerberg** [comment]
Ok, I know what the problem is. Working on a solution.

**Comment by carlhoerberg** [comment]
Working on it in #20. I think it's solved, would you like to try out this build? [dist.zip](https://github.com/cloudamqp/amqp-client.js/files/7850419/dist.zip)

**Comment by charleslukes** [comment]
Just tested and it works so far.

**Comment by carlhoerberg** [comment]
Ok! Thank you for verifying. I've released 1.3.2 now that includes this patch.
