### ISSUE TITLE
Process Is not Defined error while running from angular component

### ISSUE THREAD

**Issue by krishnareddyML** [cloudamqp/amqp-client.js#26]
I am new to this, I tried to connect one RabbitMQ server that is located in my LAN. but getting following error

ERROR ReferenceError: process is not defined
    at new AMQPClient (amqp-socket-client.js:16:1)

Following is the code I am using in component file
` 
ngOnInit(): void {
    this.run()
  }

  async run() {
    try {
      const amqp = new AMQPClient("amqp://192.168.20.57")
      const conn = await amqp.connect()
      const ch = await conn.channel()
      const q = await ch.queue()
      const consumer = await q.subscribe({noAck: true}, async (msg) => {
        console.log(msg.bodyToString())
        await consumer.cancel()
      })
      await q.publish("Hello World", {deliveryMode: 2})
      await consumer.wait() // will block until consumer is canceled or throw an error if server closed channel/connection
      await conn.close()
    } catch (e:any) {
      console.error("ERROR", e)
      e.connection.close()
      setTimeout(this.run, 1000) // will try to reconnect in 1s
    }
  }`

**Comment by carlhoerberg** [comment]
If you're connecting from a browser you need to use the `AMQPWebSocketClient`
