### ISSUE TITLE
TS Compilation Error: Cannot find name `TextDecoder`

### ISSUE THREAD

**Issue by CatalinMustata** [cloudamqp/amqp-client.js#27]
I'm running this with TypeScript 4.4.0 and I'm getting the error in the title.

I've edited `amqp-message.d.ts` to add the proper import as a temporary workaround, but I'm surprised no one complained about this, so I'm thinking maybe I'm doing something wrong.

I have not added "dom" to the list of libs in `tsconfig.json`, nor will I do that, since this is a backend server app.

Any suggestions would be much appreciated.

**Comment by carlhoerberg** [comment]
Ok, yeah, `TextEncoder` is availabe in nodejs, so i guess it's only if you manually disable `dom` in tsconfig that it will complain.

**Comment by CatalinMustata** [comment]
Thanks, Carl!

I'd argue that you manually enable `dom` instead of disabling it. Server apps should not have that enabled by default in my opinion.

Just to chime in on the fix a bit, you might be able to get away with a static decoder if you do a conditional import from `util` when running in nodejs. Not sure if there's a benefit over the `Buffer` approach though.
