### ISSUE TITLE
Connect/Disconnect

### ISSUE THREAD

**Issue by Tychus** [cloudamqp/amqp-client.js#33]
Is there anyway to get notified on events at least connect and disconnect ?

**Comment by dentarg** [comment]
https://github.com/cloudamqp/amqp-client.js/issues/25#issuecomment-1036024304 has a workaround but I admit that proper support for it would be nice!

**Comment by carlhoerberg** [comment]
the promise from `AMQPClient#connect` won't resolve until properly connected, so don't see a need for an event there. But for errors/closed I'm working on it in #35

**Comment by carlhoerberg** [comment]
`AMQPClient#onerror` is available Included in v2.1.0
