### ISSUE TITLE
amqp protocol potential bug

### ISSUE THREAD

**Issue by bytadaniel** [cloudamqp/amqp-client.js#36]
Hello! This is truly an amazing library!
I ran into a big memory leak with buffers when I was working with amqplib, but with your library the application runs very stable and consumes little volume of memory.
But, unfortunately, I cannot use your library in the enterprise, because I found some problems in the protocol itself, which I cannot solve myself.
With large read/write volumes, channels are very often closed with strange errors. I have found 2:
- frame_too_large (it writes out of volume range and fail on sending overfilled frame to rabbit)
- connection closed by server 501 FRAME_ERROR - type 3, first 16 octets = <<"{\"type\":\"save_pr">>: {invalid_frame_end_marker, 0} 0 0 (seems there is some problems with encoding or smth like that)
- ![telegram-cloud-photo-size-2-5217803838193515006-y](https://user-images.githubusercontent.com/59475531/170813972-8d9a665c-3b5b-4936-a7ee-9f33606c61e7.jpg)

**Comment by carlhoerberg** [comment]
Thank you for reporting! 

Are you sending large headers? Larger than 4KB? That might be reason for the first error. Increasing `frameMax` from 4096 to say 16*1024 would help there, you can do that in the connection URL `amqps://server?frameMax=16384`

The second problem might be related, still investigating.

**Comment by carlhoerberg** [comment]
no, you should've got another error (`RangeError`) if it was problem with too large headers. 

I rather think it's a race condition, are you sending on the same channel from multiple places?

**Comment by carlhoerberg** [comment]
In a subscribe block you're publishing again, right? That explain the problem... will try to find a solution.

**Comment by bytadaniel** [comment]
Hi! Yes, I use multiple-pod system managed by kubernetes and each process includes 1 subscribe channel and multiple producing channels (one produce channel per queue)
I didn't found a solution, so, now I am using custom version of amqplib, but I would try help you

**Comment by carlhoerberg** [comment]
I can reproduce it and have a patch soon ready.
