### ISSUE TITLE
tls support ?

### ISSUE THREAD

**Issue by AIMKK** [cloudamqp/amqp-client.js#42]
Hello,
Does amqp-client support TLS connection to  RabbitMQ? can you  post an example,please?

Thank you.

**Comment by carlhoerberg** [comment]
yes it does, just make sure that the schema in the url is `amqps`: 

```js
const amqp = new AMQPClient("amqps://my.example.com")
const conn = await amqp.connect()
```

if the servers certificate is self-signed or expired but you still want to connect then add `?insecure` to the url:
```js
const amqp = new AMQPClient("amqps://my.example.com?insecure")
const conn = await amqp.connect()
```
