### ISSUE TITLE
Support for certificate and rsa key in TLS connection

### ISSUE THREAD

**Issue by Kidel** [cloudamqp/amqp-client.js#50]
I can't find a way to setup a connection using client certificate and private key. 
amqplib has this interface https://amqp-node.github.io/amqplib/ssl.html
but I can't find anything similar here.

**Comment by Kidel** [comment]
I had to make a fork. This is the PR in case you want to include this feature (it would be much appreciated): https://github.com/cloudamqp/amqp-client.js/pull/51

**Comment by Kidel** [comment]
any update for https://github.com/cloudamqp/amqp-client.js/pull/51 ?

**Comment by carlhoerberg** [comment]
Included in 2.1.1
