### ISSUE TITLE
How to check in consumer queue is paused ?

### ISSUE THREAD

**Issue by geminigeek** [cloudamqp/amqp-client.js#52]
hi,

is there a way to check in consumer the queue is paused ?  if yes kindly mention the link where i can read about it.

thanks

**Comment by baelter** [comment]
Not atm, sound like something we should add. Thanks

**Comment by carlhoerberg** [comment]
No, there's no such thing in the protocol unfortunately. If you (re)declare a queue you get message count and consumer count back, maybe you can infer information from that.
