### ISSUE TITLE
Method for easily responding to a channel being closed

### ISSUE THREAD

**Issue by devguydavid** [cloudamqp/amqp-client.js#53]
The current documentation shows catching an error in order to reestablish a connection. This has a couple of problems:

* It may just be the channel that needs to e reestablished if the server decided to close it. In that case I don't necessarily want to recreate the entire connection.
* The entirety of the amqp code may not make sense to have inside one large try/catch block.

I see that an `onerror` callback has been added to `AMQPChannel` at https://github.com/cloudamqp/amqp-client.js/blob/ab0db59/src/amqp-channel.ts#L23 but this isn't packaged in the latest release yet. I'm assuming responding to this by recreating the channel would accomplish the server closing the channel? If so, would it be possible to create a new release with this callback included?

**Comment by dentarg** [comment]
It will be part of the next release, which will be 3.0.0. Hope to have it out soon!

**Comment by dentarg** [comment]
[v3.0.0](https://github.com/cloudamqp/amqp-client.js/releases/tag/v3.0.0) has been released now
