### ISSUE TITLE
Be able to specify timeout

### ISSUE THREAD

**Issue by everhardt** [cloudamqp/amqp-client.js#56]
It takes a very long time before a connection attempt times out. Right now there's no way to configure a connect timeout in the `AMQPClient` constructor or the `.connect()` function, which would be great to have.

For now, I wrote the following workaround:
```ts
    const connectionPromise = amqp.connect();
    amqp.socket?.setTimeout(5000);
    connection = await new Promise((resolve, reject) => {
      amqp.socket?.on('timeout', () => {
        amqp.socket?.destroy();
        reject(new DestinationError('Timeout hit'));
      });
      connectionPromise.then(resolve).catch(reject);
    });
```

**Comment by dentarg** [comment]
Pretty sure https://github.com/cloudamqp/amqp-client.js/pull/78 improved on this, are you able to check @everhardt? Using the `heartbeat` parameter you can control the timeout
