### ISSUE TITLE
Support for parallel calls

### ISSUE THREAD

**Issue by westphalen** [cloudamqp/amqp-client.js#57]
After debugging sporadic _"Consumer x not available on channel"_ errors for a long time, I have come to realise this package does not like parallel calls at all.

I would do something like

```ts
await Promise.all([
  queue.subscribe(consumeParams, callback),
  channel.exchangeBind(this.getTopic(), defaultExchange),
  queue.bind(this.getTopic(), this.routingKey),
])
```

This would cause `AMQPChannel.sendRpc` to resolve `AMQPChannel.promises` out of order, meaning sometimes `consumerTag` would come back `undefined` in `AMQPChannel.basicConsume`:
```ts
this.sendRpc(frame, j).then((consumerTag) =>  {
  const consumer = new AMQPConsumer(this, consumerTag, callback)
  this.consumers.set(consumerTag, consumer)
  resolve(consumer)
})
```

Some fundamental changes are required to make AMQPChannel support parallel calls. Would probably need to queue up one command at a time?

For now, I would suggest mentioning this pitfall in the README to prevent others running into the same issue.

**Comment by carlhoerberg** [comment]
It's completely expected that it doesn't work, you should chain the commands, that's how the protocol works.

**Comment by westphalen** [comment]
> It's completely expected that it doesn't work, you should chain the commands, that's how the protocol works. 

I am aware this is how AMQP works, what's odd is the library allows for the behaviour without error or warning. I would expect the AMQP Channel implementation to chain the promises, rather than maintaining them on an array where they end up being resolved in a random order. If I find some time I'll raise a PR for this.

**Comment by carlhoerberg** [comment]
Thank you for your report, it's fixed in main now.
