### ISSUE TITLE
[Question] This is a replacement for amqplib

### ISSUE THREAD

**Issue by gperdomor** [cloudamqp/amqp-client.js#6]
Hi, this project is intended to replace [amqplib](https://github.com/squaremo/amqp.node), at least for the nodejs side.

How compares with amqplib?

Why should we consider move from amqplib to this? (in the server-side)

**Comment by carlhoerberg** [comment]
Yes, we suggest amqplib is replaced with this. All features + more should be availabe in amqp-client.js
