### ISSUE TITLE
Connecting to non AMQP server doesn't fail

### ISSUE THREAD

**Issue by MahdiyDev** [cloudamqp/amqp-client.js#60]
```
const amqp = new AMQPClient("amqp://tmp:tmp@192.168.1.129:15672");

const conn = await amqp.connect();
```
Does not throw an error when the message queue cannot be connected.

Thanks

**Comment by KristjanTammekivi** [comment]
15672 is typically the management plugin port, are you sure you meant to use it?

**Comment by carlhoerberg** [comment]
The reporter is right, it should fail
