### ISSUE TITLE
Export AMQPBaseClient type

### ISSUE THREAD

**Issue by nasdan** [cloudamqp/amqp-client.js#63]
The `connect` method of the `AMQPBaseClient` class returns a `Promise` of type `AMQPBaseClient`, but it is not exported in the index.d.ts file, so the following code cannot be typed:

- Connect to an AMQP server (returns a `Promise` of type `AMQPBaseClient`)

```typescript
const connectToServer = async (url: string) => {
  const client = new AMQPClient(url);
  return client.connect();
};

```

- Use the connection

```typescript

const main = async () => {
  const client = await connectToServer('amqp://guest:guest@localhost:5672'); 
  // Here TypeScript can infer the type Promise<AMQPBaseClient> automatically
  await processOne(client);
}

// Here we cannot type it because the AMQPBaseClient type is not exported
const processOne = async (client) => {
  const channel = await client.channel();
 // ...
}

```

[Demo on Stackblitz](https://stackblitz.com/edit/typescript-gcngsy?file=index.ts)

**Comment by brauliodiez** [comment]
I think this issue should be reopened, I tried to install and use the library typing as is, but it just throws the error:

Steps to preoduce it:
- Created a simple nodejs + express + typescript project (I started from this one, back folder: https://github.com/Lemoncode/bootcamp-backend/tree/main/00-stack-documental/05-cloud/03-queue-and-serverless/00-boilerplate)

- Install the dependencies:

```bash
cd back
```

```bash
npm install
```

```bash
npm install @cloudamqp/amqp-client --save
```

Tried to import AMQPClient and AMQPClient 

```ts
import { AMQPClient } from "@cloudamqp/amqp-client";
import { AMQPBaseClient } from "@cloudamqp/amqp-client/types/amqp-base-client";
```

Got the following error:

```
Cannot find module '@cloudamqp/amqp-client/types/amqp-base-client' or its corresponding type declarations.
```

I had to add the following workaround in the tsconfig.json:

```diff
    "baseUrl": "./src",
    "paths": {
      "#*": ["*"],
+      "@cloudamqp/amqp-client/types/amqp-base-client": [
+        "../node_modules/@cloudamqp/amqp-client/types/amqp-base-client.d.ts"
+     ]
    }
  },
```
