### ISSUE TITLE
How to enable WebSocket on RabbitMQ?

### ISSUE THREAD

**Issue by ngbrown** [cloudamqp/amqp-client.js#7]
The documentation for this project does not mention how to configure RabbitMQ for WebSockets. Maybe this is through `websocket-tcp-relay` as described in https://www.cloudamqp.com/blog/cloudamqp-releases-amqp-websockets.html?

**Comment by carlhoerberg** [comment]
Good point! Will update the docs

**Comment by carlhoerberg** [comment]
readme is updated
