### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by jonaskello** [cloudamqp/amqp-client.js#8]
This package looks great! :-). Unfortunately my projects are all in typescript so I cannot use it in a good way as it is now. Are there any plans to support typescript? Like adding a typings file or rewriting it in typescript?

**Comment by carlhoerberg** [comment]
Yes, there is a PR with a rewrite of it in typescript: https://github.com/cloudamqp/amqp-client.js/pull/1 but it's a bit out of date now. maybe it's faster to just add some external types..

**Comment by StefanArts** [comment]
Are you planning on adding those or updating the typescript branch?

**Comment by carlhoerberg** [comment]
Can you try out https://github.com/cloudamqp/amqp-client.js/pull/12 ? It got typescript definitions generated from the jsdocs.

**Comment by carlhoerberg** [comment]
Fixed in https://github.com/cloudamqp/amqp-client.js/pull/12

**Comment by carlhoerberg** [comment]
1.3.0 is rewrite of the lib to TypeScript. Full declarations + docs are available in the package now
