### ISSUE TITLE
[TS + Node + ESM] AMQPBaseClient can't be found

### ISSUE THREAD

**Issue by PeS82** [cloudamqp/amqp-client.js#82]
When using the library in TypeScript project configured to use ESM the imports from `types` are failing.

`package.json ` has `"type": "module"`

`tsconfig`:
```json
  "compilerOptions": {
    "module": "ES2022",
    "moduleResolution": "nodenext",
    "target": "ES2022",
  }
```

The `AMQPBaseClient ` is then imported as

```typescript
import { AMQPBaseClient } from '@cloudamqp/amqp-client/types/amqp-base-client.js';`
```
and during runtime (using `ts-node-esm`) or compilation (`tsc`) it fails with error

`Cannot find module '@cloudamqp/amqp-client/types/amqp-base-client.js' or its corresponding type declarations.`

The solution I came up with is to add export to `node_modules/@cloudamqp/amqp-client/types/index.d.ts`:
```typescript
export { AMQPBaseClient } from '../types/amqp-base-client.js';
```

and then import in the project simply as
```typescript
import { AMQPBaseClient } from '@cloudamqp/amqp-client';
```

Not sure whether this is the right solution. Could you please modify the library to work with ESM?

**Comment by carlhoerberg** [comment]
Why are you importing the base client? Import the socket client.

**Comment by PeS82** [comment]
Because `amqp.connect()` (`AMQPClient`) returns  `AMQPBaseClient`.

There is exported `AMQPWebSocketClient` which is not what I want (I believe) in the server environment (i.e. not in the browser)?

**Comment by ngbrown** [comment]
In your `tsconfig.json` set `moduleResolution` to either `bundler` or `node16`. Then import like this:

```ts
import { AMQPBaseClient  } from "@cloudamqp/amqp-client/amqp-base-client";
```

**Comment by PeS82** [comment]
Thank you very much for the help, quick response and for the library. It is resolved now.
