### ISSUE TITLE
Example for Existing Exchanges and Queues

### ISSUE THREAD

**Issue by michael-rivera-florencehc-com** [cloudamqp/amqp-client.js#98]
Can an example be provided on how to publish messages to an existing exchange and listen for messages on an existing queue associated to the exchange? I have tried multiple combinations but can't get it. The existing examples dynamically generate queue, which unfortunately I cannot use. 
I appreciate any assistance on this.

**Comment by michael-rivera-florencehc-com** [comment]
I have been able to create an example. Took me a few days:

client.js
`import { AMQPChannel, AMQPClient, AMQPConsumer, AMQPQueue } from '@cloudamqp/amqp-client';

export class AmqpClientService {
  static #Instance: AmqpClientService;
  #client: AMQPClient;
  #channel: AMQPChannel;
  #connection;
  #exchangeName: string;
  #routingKey: string;
  #queueName: string;
  #queue: AMQPQueue;
  #consumer: AMQPConsumer;

  private constructor(
    client: AMQPClient,
    connection,
    channel: AMQPChannel,
    queue: AMQPQueue,
    queueName: string,
    exchangeName: string,
    routingKey: string
  ) {
    this.#client = client;
    this.#channel = channel;
    this.#exchangeName = exchangeName;
    this.#routingKey = routingKey;
    this.#queueName = queueName;
    this.#queue = queue;
    this.#connection = connection;
  }

  public static async init(
    uri: string,
    queueName: string,
    exchange: string,
    routingKey: string
  ) {
    if (this.#Instance) {
      return this.#Instance;
    }
    const client = new AMQPClient(uri);
    const conn = await client.connect();
    const ch = await conn.channel();
    const qu = await ch.queue(
      queueName,
      { durable: true },
      {
        'x-dead-letter-exchange': 'EBINDER_DEAD_LETTER_EXCHANGE',
        'x-dead-letter-routing-key': 'DOCUMENT_DRIVEN_STUDY_STARTUP',
        'x-max-in-memory-length': 1,
        'x-delivery-limit': 3,
        'x-queue-type': 'quorum',
      }
    );
    await qu.bind(exchange, routingKey);

    return (this.#Instance = new AmqpClientService(
      client,
      conn,
      ch,
      qu,
      queueName,
      exchange,
      routingKey
    ));
  }

  async subscribe() {
    try {
      
      this.#consumer = await this.#queue.subscribe(
        { noAck: false, },
        async (msg) => {
          console.log(msg);
        })

      await this.#consumer.wait();
    } catch (e) {
      console.error('ERROR', e);
      e.connection.close();
      setTimeout(this.subscribe, 5000); // will try to reconnect in 1s
    }
  }

  async publish(message: string) {
    try {
      await this.#channel.basicPublish(
        this.#exchangeName,
        this.#routingKey,
        Buffer.from(message, 'utf-8'),
        { deliveryMode: 2 }
      );
    } catch (e) {
      console.error('ERROR', e);
      e.connection.close();
      setTimeout(this.publish, 5000, message);
    }
  }

  async close() {
    await this.#consumer.cancel();
    await this.#client.close();
    await this.#connection.close();
  }
}
`

bootstrap.js - publish a message and consume a message
`import { AmqpClientService } from '../shared/services/amqp-client-service.js'
import { ConfigurationService } from '../shared/services/configuration-service.js';

const location = 'QAUS'
const configuration = new ConfigurationService(
  [
    'AMQP_SERVICE_URI',
    'AMQP_SERVICE_QUEUE',
    'AMQP_SERVICE_EXCHANGE',
    'AMQP_SERVICE_ROUTING_KEY'
  ],
  `.env.${location}`
);

const {
  AMQP_SERVICE_URI,
  AMQP_SERVICE_QUEUE,
  AMQP_SERVICE_EXCHANGE,
  AMQP_SERVICE_ROUTING_KEY
} = configuration.environmentVariables;

const amqpClientService = await AmqpClientService.init(AMQP_SERVICE_URI, AMQP_SERVICE_QUEUE, AMQP_SERVICE_EXCHANGE, AMQP_SERVICE_ROUTING_KEY);
console.log(`Waiting for Messages from ${AMQP_SERVICE_QUEUE}`);
amqpClientService.subscribe();


while(true) {
  const str = randomCharacters(24);
  console.log(`Sending a Message - ${str}`)
  amqpClientService.publish(JSON.stringify({ message: `This is a test for ${str}`}))
  await wait(5000);
}

function wait(milliSeconds){
  return new Promise(res=>setTimeout(res,milliSeconds));
}

function randomCharacters(length){
  const chars =
    'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz1234567890';
  const randomArray = Array.from(
    { length: length },
    (_, __) => chars[Math.floor(Math.random() * chars.length)]
  );

  const randomString = randomArray.join('');
  return randomString;
}`

**Comment by baelter** [comment]
If you expect the amqp resource to already exist you can set the passive flag when declaring the resources.
